name: ci

on:
  push:
    branches: [main]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format Check
        run: npm run format:check

      - name: Lint Check
        run: bun run lint
